import Foundation

/// Type-safe localization keys — use L10n.key.localized
enum L10n {
    // MARK: - Common
    static let save = "common.button.save"
    static let cancel = "common.button.cancel"
    static let delete = "common.button.delete"
    static let done = "common.button.done"
    static let copied = "common.label.copied"
    static let none = "common.label.none"

    // MARK: - Tabs
    static let tabExtract = "tabs.extract"
    static let tabCamera = "tabs.camera"
    static let tabLibrary = "tabs.library"
    static let tabSettings = "tabs.settings"

    // MARK: - Extraction
    static let extractionTitle = "extraction.title"
    static let extractionChoosePhoto = "extraction.toolbar.choosephoto"
    static let extractionEmptyTitle = "extraction.empty.title"
    static let extractionEmptyButton = "extraction.empty.button"
    static let extractionEmptyButtonA11y = "extraction.empty.button.accessibility"
    static let extractionImageA11y = "extraction.image.accessibility"
    static let extractionPaletteTitle = "extraction.palette.title"
    static let extractionPaletteCount = "extraction.palette.colorcount"
    static let extractionSavePalette = "extraction.button.savepalette"
    static let extractionSavePaletteA11y = "extraction.button.savepalette.accessibility"
    static let extractionSaveTitle = "extraction.save.title"
    static let extractionSavePlaceholder = "extraction.save.placeholder"
    static let extractionSaveDefault = "extraction.save.default"

    // MARK: - Camera
    static let cameraTitle = "camera.title"
    static let cameraAddA11y = "camera.button.add.accessibility"
    static let cameraSaveTitle = "camera.save.title"
    static let cameraSavePlaceholder = "camera.save.placeholder"
    static let cameraSaveDefault = "camera.save.default"
    static let cameraPermissionTitle = "camera.permission.title"
    static let cameraPermissionMessage = "camera.permission.message"
    static let cameraPermissionButton = "camera.permission.button"
    static let cameraUnavailableTitle = "camera.unavailable.title"
    static let cameraUnavailableMessage = "camera.unavailable.message"
    static let cameraPickedTitle = "camera.picked.title"
    static let cameraSavePalette = "camera.button.savepalette"

    // MARK: - Library
    static let libraryTitle = "library.title"
    static let librarySearchPrompt = "library.search.prompt"
    static let libraryEmptyTitle = "library.empty.title"
    static let libraryEmptySubtitle = "library.empty.subtitle"
    static let librarySearchNoResults = "library.search.noresults"
    static let libraryRowColorCount = "library.row.colorcount"
    static let libraryRowA11y = "library.row.accessibility"

    // MARK: - Detail
    static let detailTitle = "detail.title"
    static let detailAutoAssign = "detail.toolbar.autoassign"
    static let detailExport = "detail.toolbar.export"
    static let detailNamePlaceholder = "detail.name.placeholder"
    static let detailNameEditA11y = "detail.name.edit.accessibility"
    static let detailSectionColors = "detail.section.colors"
    static let detailSectionContrast = "detail.section.contrast"
    static let detailSectionPreview = "detail.section.preview"
    static let detailContrastSameColor = "detail.contrast.samecolor"
    static let detailContrastA11y = "detail.contrast.accessibility"
    static let detailEmptyColors = "detail.empty.colors"
    static let detailContrastLegendAAA = "detail.contrast.legend.aaa"
    static let detailContrastLegendAA = "detail.contrast.legend.aa"
    static let detailContrastLegendLarge = "detail.contrast.legend.large"
    static let detailContrastLegendFail = "detail.contrast.legend.fail"
    static let detailContrastHint = "detail.contrast.hint"
    static let detailContrastInfoTitle = "detail.contrast.info.title"
    static let detailContrastInfoBody = "detail.contrast.info.body"
    static let detailContrastInfoButton = "detail.contrast.info.button"
    static let detailContrastTooltipFg = "detail.contrast.tooltip.foreground"
    static let detailContrastTooltipBg = "detail.contrast.tooltip.background"
    static let detailContrastTooltipRatio = "detail.contrast.tooltip.ratio"
    static let detailContrastTooltipNormal = "detail.contrast.tooltip.normal"
    static let detailContrastTooltipLarge = "detail.contrast.tooltip.large"
    static let detailContrastTooltipFix = "detail.contrast.tooltip.fix"

    // MARK: - Color Detail
    static let colorDetailRoleA11y = "colordetail.role.accessibility"

    // MARK: - Swatch
    static let swatchA11yLabel = "swatch.accessibility.label"
    static let swatchA11yHint = "swatch.accessibility.hint"
    static let swatchCopyHex = "swatch.context.copyhex"
    static let swatchCopyRGB = "swatch.context.copyrgb"
    static let swatchRemove = "swatch.context.remove"

    // MARK: - Magnifier
    static let magnifierA11y = "magnifier.accessibility"

    // MARK: - Export
    static let exportTitle = "export.title"
    static let exportFormatLabel = "export.format.label"
    static let exportCopy = "export.button.copy"
    static let exportShare = "export.button.share"
    static let exportDone = "export.button.done"

    // MARK: - Preview
    static let previewTitle = "preview.title"
    static let previewButton = "preview.button"
    static let previewBody = "preview.body"
    static let previewTag1 = "preview.tag1"
    static let previewTag2 = "preview.tag2"
    static let previewTag3 = "preview.tag3"
    static let previewA11y = "preview.accessibility"
    static let previewRoleHint = "preview.rolehint"
    static let previewAutoAssign = "preview.autoassign"
    static let previewStyleApp = "preview.style.app"
    static let previewStyleDashboard = "preview.style.dashboard"
    static let previewStyleBlog = "preview.style.blog"
    static let previewDashboardUsers = "preview.dashboard.users"
    static let previewDashboardRevenue = "preview.dashboard.revenue"
    static let previewDashboardGrowth = "preview.dashboard.growth"
    static let previewDashboardProgress = "preview.dashboard.progress"
    static let previewDashboardChart = "preview.dashboard.chart"
    static let previewBlogTitle = "preview.blog.title"
    static let previewBlogExcerpt = "preview.blog.excerpt"
    static let previewBlogAuthor = "preview.blog.author"
    static let previewBlogReadMore = "preview.blog.readmore"
    static let previewBlogDate = "preview.blog.date"

    // MARK: - Settings
    static let settingsTitle = "settings.title"
    static let settingsAppearance = "settings.section.appearance"
    static let settingsThemeLabel = "settings.theme.label"
    static let settingsThemeLight = "settings.theme.light"
    static let settingsThemeDark = "settings.theme.dark"
    static let settingsThemeSystem = "settings.theme.system"
    static let settingsLanguageSection = "settings.section.language"
    static let settingsLanguageLabel = "settings.language.label"
    static let settingsGeneral = "settings.section.general"
    static let settingsHaptic = "settings.haptic.label"
    static let settingsColorCount = "settings.colorcount.label"
    static let settingsExportFormat = "settings.export.label"
    static let settingsAbout = "settings.section.about"
    static let settingsVersion = "settings.version"

    // MARK: - Color Harmony
    static let harmonyTitle = "harmony.title"
    static let harmonySourceColor = "harmony.source"
    static let harmonyComplementary = "harmony.type.complementary"
    static let harmonyAnalogous = "harmony.type.analogous"
    static let harmonyTriadic = "harmony.type.triadic"
    static let harmonySplitComplementary = "harmony.type.splitcomplementary"
    static let harmonyTetradic = "harmony.type.tetradic"
    static let harmonyComplementaryDesc = "harmony.desc.complementary"
    static let harmonyAnalogousDesc = "harmony.desc.analogous"
    static let harmonyTriadicDesc = "harmony.desc.triadic"
    static let harmonySplitComplementaryDesc = "harmony.desc.splitcomplementary"
    static let harmonyTetradicDesc = "harmony.desc.tetradic"
    static let harmonySaveAsPalette = "harmony.button.save"
    static let harmonySaveTitle = "harmony.save.title"
    static let harmonySavePlaceholder = "harmony.save.placeholder"
    static let harmonySaveDefault = "harmony.save.default"
    static let harmonyGenerate = "harmony.button.generate"
    static let harmonyA11y = "harmony.accessibility"
    static let harmonyColorA11y = "harmony.color.accessibility"

    // MARK: - Palette Comparison
    static let comparisonTitle = "comparison.title"
    static let comparisonSelectFirst = "comparison.select.first"
    static let comparisonSelectSecond = "comparison.select.second"
    static let comparisonVs = "comparison.vs"
    static let comparisonSummary = "comparison.summary"
    static let comparisonAvgDeltaE = "comparison.avg.deltae"
    static let comparisonDeltaE = "comparison.deltae"
    static let comparisonBadgeIdentical = "comparison.badge.identical"
    static let comparisonBadgeSimilar = "comparison.badge.similar"
    static let comparisonBadgeDifferent = "comparison.badge.different"
    static let comparisonBadgeVeryDifferent = "comparison.badge.verydifferent"
    static let comparisonUnmatched = "comparison.unmatched"
    static let comparisonA11y = "comparison.accessibility"
    static let comparisonPairA11y = "comparison.pair.accessibility"
    static let comparisonCompare = "comparison.button.compare"

    // MARK: - Color Blindness Simulator
    static let blindnessTitle = "blindness.title"
    static let blindnessNormal = "blindness.type.normal"
    static let blindnessProtanopia = "blindness.type.protanopia"
    static let blindnessDeuteranopia = "blindness.type.deuteranopia"
    static let blindnessTritanopia = "blindness.type.tritanopia"
    static let blindnessNormalDesc = "blindness.desc.normal"
    static let blindnessProtanopiaDesc = "blindness.desc.protanopia"
    static let blindnessDeuteranopiaDesc = "blindness.desc.deuteranopia"
    static let blindnessTritanopiaDesc = "blindness.desc.tritanopia"
    static let blindnessOriginal = "blindness.label.original"
    static let blindnessSimulated = "blindness.label.simulated"
    static let blindnessDeltaE = "blindness.deltae"
    static let blindnessWarning = "blindness.warning"
    static let blindnessNoIssues = "blindness.noissues"
    static let blindnessConfusable = "blindness.confusable"
    static let blindnessA11y = "blindness.accessibility"
    static let blindnessPairA11y = "blindness.pair.accessibility"
    static let blindnessSimulate = "blindness.button.simulate"

    // MARK: - Image Analysis
    static let analysisTitle = "analysis.title"
    static let analysisDominant = "analysis.dominant"
    static let analysisWarmCool = "analysis.warmcool"
    static let analysisWarm = "analysis.warm"
    static let analysisCool = "analysis.cool"
    static let analysisSaturation = "analysis.saturation"
    static let analysisBrightness = "analysis.brightness"
    static let analysisLow = "analysis.low"
    static let analysisMedium = "analysis.medium"
    static let analysisHigh = "analysis.high"
    static let analysisDark = "analysis.dark"
    static let analysisMid = "analysis.mid"
    static let analysisLight = "analysis.light"
    static let analysisMood = "analysis.mood_label"
    static let analysisMoodWarmVibrant = "analysis.mood.warm_vibrant"
    static let analysisMoodWarmMuted = "analysis.mood.warm_muted"
    static let analysisMoodCoolVibrant = "analysis.mood.cool_vibrant"
    static let analysisMoodCoolMuted = "analysis.mood.cool_muted"
    static let analysisMoodNeutral = "analysis.mood.neutral_balanced"
    static let analysisMoodDarkMoody = "analysis.mood.dark_moody"
    static let analysisMoodLightAiry = "analysis.mood.light_airy"
    static let analysisMoodColorful = "analysis.mood.colorful"
    static let analysisCoverage = "analysis.coverage"
    static let analysisA11y = "analysis.accessibility"
    static let analysisAnalyze = "analysis.button.analyze"

    // MARK: - Sharing
    static let shareTitle = "share.title"
    static let shareLink = "share.link"
    static let shareQRCode = "share.qrcode"
    static let shareCopy = "share.copy"
    static let shareButton = "share.button"
    static let shareA11y = "share.accessibility"
    static let shareImported = "share.imported"
    static let shareInvalidLink = "share.invalid_link"
    static let shareNotFound = "share.not_found"

    // MARK: - Widget
    static let widgetSetAs = "widget.set_as"
    static let widgetSetConfirm = "widget.set_confirm"
    static let widgetA11y = "widget.accessibility"
}

